from emojis import encode

SQL_UID = "UID"
SQL_VERIFIED = "VERIFIED"
SQL_IGN = "IGN"
SQL_ALT = "ALT"
SQL_O3 = "O3"
SQL_RUNS = "RUNS"
SQL_KEY_POPS = "KEY_POPS"
SQL_RUNES = "RUNES"
SQL_VIALS = "VIALS"
SQL_POINTS = "POINTS"

SQL_CONFIG_TABLE_NAME = "ServerConfig"
SQL_CONFIG_GID = "GID"
SQL_CONFIG_RANK_MINIMUM = "MIN_RANK"
SQL_CONFIG_VERIFIED_ROLE_ID = "VERIFIED_ROLE_ID"
SQL_CONFIG_RAID_CHANNEL_ID = "RAID_CHANNEL_ID"
SQL_CONFIG_DUNGEON_ROLES = "DUNGEON_ROLES"
SQL_CONFIG_EMOJI_DATA = "EMOJI_DATA"
SERVER_CONFIG_DB = 'server_configs.json'

EMOJI_CONFIRM = encode(":white_check_mark:")