from enum import Enum

SQL_UID = "UID"
SQL_VERIFIED = "VERIFIED"
SQL_IGN = "IGN"
SQL_ALT = "ALT"
SQL_O3 = "O3"
SQL_RUNS = "RUNS"
SQL_KEY_POPS = "KEY_POPS"
SQL_RUNES = "RUNES"
SQL_VIALS = "VIALS"
SQL_POINTS = "POINTS"


CONFIG_VERIFIED_ROLE_ID = "verified-role"
CONFIG_DUNGEON_ROLES = "dungeon-roles"
CONFIG_DUNGEON_ROLE = "role"
CONFIG_DUNGEON_ROLE_ID = "id"
CONFIG_DUNGEON_ROLE_EMOJI = "emoji"
