from enum import Enum

SQL_UID = "UID"
SQL_VERIFIED = "VERIFIED"
SQL_IGN = "IGN"
SQL_ALT = "ALT"
SQL_O3 = "O3"
SQL_RUNS = "RUNS"
SQL_KEY_POPS = "KEY_POPS"
SQL_RUNES = "RUNES"
SQL_VIALS = "VIALS"
SQL_POINTS = "POINTS"
